/**
 * <p>Copyright (c) The National Archives 2005-2010.  All rights reserved.
 * See Licence.txt for full licence details.
 * <p/>
 *
 * <p>DROID DCS Profile Tool
 * <p/>
 */
package uk.gov.nationalarchives.droid.gui.report;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.List;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JRadioButton;
import javax.swing.SwingWorker;
import javax.swing.WindowConstants;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import org.openide.util.NbBundle;

import uk.gov.nationalarchives.droid.gui.GlobalContext;

/**
 * Report Dialog.
 * 
 * @author Alok Kumar Dash
 */
public class ReportDialog extends JDialog {

    private static final long serialVersionUID = -8918459838713781052L;
    private static final String STATE = "state";
    private ReportAction action;
    private List<String> profileIds;
    private GlobalContext globalContext;

    /**
     * Creates new form ReportDialog.
     * 
     * @param parent
     *            the dialog's parent
     * @param profileIds
     *            profileIds.
     * @param globalContext
     *            Global Context.
     */
    public ReportDialog(Frame parent, List<String> profileIds,
            GlobalContext globalContext) {
        super(parent);
        initComponents();
        buttonGroup1.add(radioButtonByPUID);
        buttonGroup1.add(radioButtonByYear);
        pack();
        setLocationRelativeTo(parent);
        this.profileIds = profileIds;
        this.globalContext = globalContext;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        cancelButton = new JButton();
        reportProgressBar = new JProgressBar();
        jLabel1 = new JLabel();
        jButtonOk = new JButton();
        radioButtonByYear = new JRadioButton();
        radioButtonByPUID = new JRadioButton();

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(NbBundle.getMessage(ReportDialog.class, "ReportDialog.title")); // NOI18N
        setModal(true);
        setResizable(false);

        cancelButton.setText(NbBundle.getMessage(ReportDialog.class,
                "ReportDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(NbBundle.getMessage(ReportDialog.class,
                "ReportDialog.jLabel1.text")); // NOI18N
        jButtonOk.setText(NbBundle.getMessage(ReportDialog.class,
                "ReportDialog.jButtonOk.text")); // NOI18N
        jButtonOk.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        radioButtonByYear.setText(NbBundle.getMessage(ReportDialog.class,
                "ReportDialog.radioButtonByYear.text")); // NOI18N
        radioButtonByPUID.setText(NbBundle.getMessage(ReportDialog.class,
                "ReportDialog.radioButtonByPUID.text")); // NOI18N
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout
                .setHorizontalGroup(layout
                        .createParallelGroup(Alignment.LEADING)
                        .addGroup(
                                layout
                                        .createSequentialGroup()
                                        .addGroup(
                                                layout
                                                        .createParallelGroup(
                                                                Alignment.LEADING)
                                                        .addGroup(
                                                                layout
                                                                        .createSequentialGroup()
                                                                        .addGroup(
                                                                                layout
                                                                                        .createParallelGroup(
                                                                                                Alignment.LEADING,
                                                                                                false)
                                                                                        .addGroup(
                                                                                                layout
                                                                                                        .createSequentialGroup()
                                                                                                        .addGap(
                                                                                                                96,
                                                                                                                96,
                                                                                                                96)
                                                                                                        .addComponent(
                                                                                                                jButtonOk,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                66,
                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                        .addGap(
                                                                                                                18,
                                                                                                                18,
                                                                                                                18))
                                                                                        .addGroup(
                                                                                                Alignment.TRAILING,
                                                                                                layout
                                                                                                        .createSequentialGroup()
                                                                                                        .addContainerGap(
                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                        .addComponent(
                                                                                                                radioButtonByPUID)
                                                                                                        .addGap(
                                                                                                                32,
                                                                                                                32,
                                                                                                                32)))
                                                                        .addPreferredGap(
                                                                                ComponentPlacement.RELATED)
                                                                        .addGroup(
                                                                                layout
                                                                                        .createParallelGroup(
                                                                                                Alignment.TRAILING)
                                                                                        .addComponent(
                                                                                                cancelButton)
                                                                                        .addComponent(
                                                                                                radioButtonByYear)))
                                                        .addGroup(
                                                                layout
                                                                        .createSequentialGroup()
                                                                        .addGap(
                                                                                119,
                                                                                119,
                                                                                119)
                                                                        .addComponent(
                                                                                jLabel1))
                                                        .addGroup(
                                                                layout
                                                                        .createSequentialGroup()
                                                                        .addGap(
                                                                                47,
                                                                                47,
                                                                                47)
                                                                        .addComponent(
                                                                                reportProgressBar,
                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                243,
                                                                                GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(29, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
                .addGroup(
                        Alignment.TRAILING,
                        layout.createSequentialGroup().addContainerGap(22,
                                Short.MAX_VALUE).addComponent(jLabel1).addGap(
                                18, 18, 18).addGroup(
                                layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(radioButtonByPUID)
                                        .addComponent(radioButtonByYear))
                                .addGap(18, 18, 18).addGroup(
                                        layout.createParallelGroup(
                                                Alignment.BASELINE)
                                                .addComponent(jButtonOk)
                                                .addComponent(cancelButton))
                                .addGap(18, 18, 18).addComponent(
                                        reportProgressBar,
                                        GroupLayout.PREFERRED_SIZE,
                                        GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
        if (action != null) {
            if (action.getState().equals(SwingWorker.StateValue.STARTED)) {
                action.cancel(true);
            }
        }
        dispose();

    }// GEN-LAST:event_cancelButtonActionPerformed

    private void jButtonOkActionPerformed(ActionEvent evt) {// GEN-FIRST:event_jButtonOkActionPerformed
        action = globalContext.getActionFactory().newReportAction();

        action.setProfileIds(profileIds);

        action.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (STATE.equals(evt.getPropertyName())
                        && evt.getNewValue()
                                .equals(SwingWorker.StateValue.DONE)) {
                    dispose();
                }
            }
        });

        reportProgressBar.setIndeterminate(true);
        jButtonOk.disable();
        action.execute();

    }// GEN-LAST:event_jButtonOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup1;
    private JButton cancelButton;
    private JButton jButtonOk;
    private JLabel jLabel1;
    private JRadioButton radioButtonByPUID;
    private JRadioButton radioButtonByYear;
    private JProgressBar reportProgressBar;
    // End of variables declaration//GEN-END:variables

}
