/**
 * <p>Copyright (c) The National Archives 2005-2010.  All rights reserved.
 * See Licence.txt for full licence details.
 * <p/>
 *
 * <p>DROID DCS Profile Tool
 * <p/>
 */
package uk.gov.nationalarchives.droid.gui.filter;

import java.awt.Color;
import java.awt.Dialog;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JTextField;

import uk.gov.nationalarchives.droid.gui.filter.domain.GenericMetadata;
import uk.gov.nationalarchives.droid.profile.FilterCriterionImpl;

/**
 * @author Alok Kumar Dash
 */
public class TextBoxAndButton extends javax.swing.JPanel {

    /** */
    private static final long serialVersionUID = -1248240900794717169L;
    private Dialog parent;
    private GenericMetadata metadata;
    private FilterCriterionImpl filterCriteria;

    /**
     * Creates new form TextBoxAndButton.
     * 
     * @param parent
     *            the parent dialog
     */
    public TextBoxAndButton(Dialog parent) {
        this.parent = parent;
        initComponents();
        jButtonShowValues.setText("..."); // NOI18N
    }

    /**
     * FIXME: javadoc.
     * 
     * @param genericMetadata
     *            FIXME: javadoc
     * @param criteria
     *            FIXME: javadoc
     */
    public void setType(GenericMetadata genericMetadata,
            FilterCriterionImpl criteria) {
        this.metadata = genericMetadata;
        this.filterCriteria = criteria;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtextValues = new javax.swing.JTextField();
        jButtonShowValues = new javax.swing.JButton();

        // jtextValues.setText(org.openide.util.NbBundle.getMessage(TextBoxAndButton.class,
        // "TextBoxAndButton.jtextValues.text")); // NOI18N
        jtextValues.setMargin(new java.awt.Insets(0, 0, 0, 0));

        // jButtonShowValues.setText(org.openide.util.NbBundle.getMessage(TextBoxAndButton.class,
        // "TextBoxAndButton.jButtonShowValues.text")); // NOI18N
        jButtonShowValues
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonShowValuesActionPerformed(evt);
                    }
                });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addComponent(jtextValues,
                        javax.swing.GroupLayout.DEFAULT_SIZE, 271,
                        Short.MAX_VALUE).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonShowValues,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtextValues,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 24,
                                Short.MAX_VALUE).addComponent(
                                jButtonShowValues,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 24,
                                Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowValuesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonShowValuesActionPerformed

        ValuesDialog dialog = new ValuesDialog(parent, true, metadata,
                filterCriteria);
        dialog.setTitle(metadata.getMetadataName().getName());
        
        dialog.setVisible(true);
        jtextValues.setText(dialog.getSelectedString());

    }// GEN-LAST:event_jButtonShowValuesActionPerformed

    /**
     * @return FIXME: javadoc
     */
    public JButton getButton() {
        return jButtonShowValues;
    }

    /**
     * 
     * @return FIXME: javadoc
     */
    public JTextField getTextField() {
        return jtextValues;
    }

    /**
     * 
     * FIXME: javadoc.
     */
    public void hide() {

        jButtonShowValues.hide();
        jtextValues.hide();

    }

    /**
     * 
     * FIXME: javadoc.
     */
    public void show() {
        jButtonShowValues.show();
        jtextValues.show();
    }

    /**
     * 
     * FIXME: javadoc.
     */
    public void paintRedBoxToComponents() {
        jtextValues.setBorder(BorderFactory.createLineBorder(Color.red));
        repaint();
    }

    /**
     * 
     * FIXME: javadoc.
     */
    public void clearRedBoxToComponents() {
        jtextValues.setBorder(null);

        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonShowValues;
    private javax.swing.JTextField jtextValues;
    // End of variables declaration//GEN-END:variables

}
